name: Update PubMed Plot

on:
  schedule:
    - cron: '0 0 1 * *' # Esegue lo script il primo giorno di ogni mese
  workflow_dispatch: # Consente esecuzione manuale

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install biopython pandas matplotlib

      - name: Run script
        run: |
          python plot.py
          
      - name: Upload plot artifact
        uses: actions/upload-artifact@v4
        with:
          name: PubMed-plot
          path: MC_PubMed.png

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update PubMed Monte Carlo plot"
